name = "divortio-pushid"
main = "src/index.mjs"
compatibility_date = "2025-08-15"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

minify = true
workers_dev = false
preview_urls = false


[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1

# This binds the './public' directory to your Worker, making the assets
# available via the `env.ASSETS` service binding.
[assets]
binding = "ASSETS"
directory = "./public"

[[routes]]
pattern = "pushid.tools.divort.io"
custom_domain = true